package sample;
import java.sql.SQLOutput

global Controller controller;

rule "Who is it for?"
    when

    then
        Question question = new Question("Who is it for?");
        question.getPossibleAnswers().add("Personal use");
        question.getPossibleAnswers().add("Someone else");
        controller.getNewQuestion(question);
end


rule "It's for personal use"
    when
        a: Answer(text == "Personal use", questionText == "Who is it for?")
    then
        Question question = new Question("Are you at home?");
        question.getPossibleAnswers().add("Yes");
        question.getPossibleAnswers().add("No");
        controller.getNewQuestion(question);
end


rule "It's for someone else"
    when
        a: Answer(text == "Someone else", questionText == "Who is it for?")
    then
        Question question = new Question("Are you at a social gathering?");
        question.getPossibleAnswers().add("Yes");
        question.getPossibleAnswers().add("No");
        controller.getNewQuestion(question);
end


rule "I'm at a social gathering"
    when
        a: Answer(text == "Yes", questionText == "Are you at a social gathering?")
    then
        Question question = new Question("What kind of gathering?");
        question.getPossibleAnswers().add("Art opening");
        question.getPossibleAnswers().add("Beach BBQ");
        question.getPossibleAnswers().add("Dinner party");
        question.getPossibleAnswers().add("Bachelor(ette) party");
        question.getPossibleAnswers().add("Get together");
        controller.getNewQuestion(question);
end


rule "I'm not at a social gathering"
    when
         a1: Answer(text == "Yes", questionText == "Do you know them?") or
         a2: Answer(text == "No", questionText == "Are you at a social gathering?")
    then
        Question question = new Question("Are they wine lovers?");
        question.getPossibleAnswers().add("Yes");
        question.getPossibleAnswers().add("No");
        controller.getNewQuestion(question);
end


rule "They're wine lovers"
    when
        a: Answer(text == "Yes", questionText == "Are they wine lovers?")
        a2: Answer(text == "No", questionText == "Are you at a social gathering?")
    then
        Question question = new Question("Do you really know them?");
        question.getPossibleAnswers().add("Yes");
        question.getPossibleAnswers().add("No");
        controller.getNewQuestion(question);
end


rule "They aren't wine lovers"
    when
        a: Answer(text == "No", questionText == "Are they wine lovers?")
    then
        FinshResult result =  new FinshResult("They don't deserve wine. Get out of my flowchart");
        controller.getFinishResult(result);
end


rule "I really know them"
    when
        a: Answer(text == "Yes", questionText == "Do you really know them?") or
        (a1: Answer(text == "Yes", questionText == "Are they wine lovers?") and
        a2: Answer(text == "Yes", questionText == "Do you know them?"))
    then
        Question question = new Question("Are they your favourite people in the world? Be honest.");
        question.getPossibleAnswers().add("Yes");
        question.getPossibleAnswers().add("No");
        controller.getNewQuestion(question);
end


rule "I not really know them"
    when
        a: Answer(text == "No", questionText == "Do you really know them?")
    then
        FinshResult result =  new FinshResult("They don't deserve wine. Get out of my flowchart");
        controller.getFinishResult(result);
end


rule "They are my favourite people in the world"
    when
        a: Answer(text == "Yes", questionText == "Are they your favourite people in the world? Be honest.")
    then
        FinshResult result =  new FinshResult("Hedonistic joy ride CALIFORNIA PINOT NOIR");
        controller.getFinishResult(result);
end


rule "They aren't my favourite people in the world"
    when
        a: Answer(text == "No", questionText == "Are they your favourite people in the world? Be honest.")
    then
        FinshResult result =  new FinshResult("They don't deserve wine. Get out of my flowchart");
        controller.getFinishResult(result);
end


rule "It is art opening"
    when
        a: Answer(text == "Art opening", questionText == "What kind of gathering?")
    then
        FinshResult result =  new FinshResult("They rarely have a sense of taste 2-BUCK CHUCK");
        controller.getFinishResult(result);
end


rule "It's beach BBQ"
    when
        a: Answer(text == "Beach BBQ", questionText == "What kind of gathering?")
    then
        FinshResult result =  new FinshResult("Bought a nice bottle but it was confiscated. No glass on the beach");
        controller.getFinishResult(result);
end


rule "It's a dinner party"
    when
        a: Answer(text == "Dinner party", questionText == "What kind of gathering?")
    then
        Question question = new Question("Who is cooking?");
        question.getPossibleAnswers().add("Them");
        question.getPossibleAnswers().add("Me");
        controller.getNewQuestion(question);
end


rule "They are cooking"
    when
        a: Answer(text == "Them", questionText == "Who is cooking?")
    then
        FinshResult result =  new FinshResult("Buy the biggest bottle WITH THE WORDS 'RED BLEND'");
        controller.getFinishResult(result);
end


rule "I am cooking"
    when
        a: Answer(text == "Me", questionText == "Who is cooking?")
    then
        FinshResult result =  new FinshResult("They don't deserve wine. Get out of my flowchart");
        controller.getFinishResult(result);
end


rule "It's bachelor(ette) party"
    when
        a: Answer(text == "Bachelor(ette) party", questionText == "What kind of gathering?")
    then
        FinshResult result =  new FinshResult("Leave your wine at home BRING WHISKEY OR VODKA");
        controller.getFinishResult(result);
end


rule "It's get together"
    when
        a: Answer(text == "Get together", questionText == "What kind of gathering?")
    then
        Question question = new Question("Do you know them?");
        question.getPossibleAnswers().add("Yes");
        question.getPossibleAnswers().add("No");
        controller.getNewQuestion(question);
end


rule "I know them"
    when
        a: Answer(text == "Yes", questionText == "Do you know them?")
    then
        Question question = new Question("Are they wine lovers?");
        question.getPossibleAnswers().add("Yes");
        question.getPossibleAnswers().add("No");
        controller.getNewQuestion(question);
end


rule "I don't know them"
    when
        a: Answer(text == "No", questionText == "Do you know them?")
    then
        FinshResult result =  new FinshResult("Bring a boring bottle & HOPE NO ONE OPENS IT");
        controller.getFinishResult(result);
end

